version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@hapi/hapi"
    versions:
    - 20.1.0
    - 20.1.1
  - dependency-name: "@hapi/lab"
    versions:
    - 24.1.0
    - 24.1.1
